# Generated by Django 5.0.6 on 2024-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_patient_admittance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admittance_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='default_first_name', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='default_sex', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='default_patient_id', max_length=100),
        ),
    ]
