# Generated by Django 5.0.6 on 2024-07-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patient_admittance_date_patient_birthday_and_more'),
        ('api', '0006_alter_patient_aufnahmedatum_and_more'),
    ]

    operations = [
    ]
