# Generated by Django 5.0.6 on 2024-07-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_patient_admittance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnose',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
